# Generated by Django 3.2.8 on 2021-12-22 12:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_delete_plan'),
    ]

    operations = [
        migrations.AlterField(
            model_name='report',
            name='home',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.home'),
        ),
    ]
